import type { Metadata } from "next";

// import Roboto_Flex loader function from nextjs built-in
import { Roboto_Flex } from "next/font/google";
import "./globals.css";

const robotoFlex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
  display: "swap",  // so the browser uses a fallback font immediately and swaps to Roboto_Flex when it finishes loading (prevents invisible text)
  axes: ["wdth", "slnt", "opsz"]
});

// export a metadata constant typed as Metadata
// this metadata becomes part of the <head> tags Next.js injects.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // wrapped children route
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.variable} antialiased`}  // "antialiased" is a CSS utility class that enables font-smoothing (reduces jagged edges on text). This class name frequently comes from Tailwind CSS (but it can be defined anywhere). It improves text rendering on some displays.
      >
        {children}
      </body>
    </html>
  );
}
