// this file is referred to as the "root layout"
// the "root layout" is the mandatory layout for every Next.js application!
// next.js automatically generates this file even if we delete it !

// let's define the "metadata object"
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

// every layout component (RootLayout) should accept the children prop
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                
                {/* Although the "Header" and "Footer" can be a separate component, but here just for demo we will use placeholder text! */}
                <header style={{
                    backgroundColor: "lightblue",
                    padding: "1rem",
                }}>
                    <p>Header</p>
                </header>

                {children} {/* The children prop here, represents the "Home" component defined in "page.tsx" and it could be anything else depends on the routes! For instance, if we navigate to /products route, the children prop will render that subsequent portion! */}

                <footer style={{
                    backgroundColor: "ghostwhite",
                    padding: "1rem",
                }}>
                    <p>Footer</p>
                </footer>

            </body>
        </html>
    )
}

// As the "Header" and "Footer" are the part of the layout, even if we navigate to some different route, they will be present over there as well!