/* 
  => This file is the main entry point of our application, and all the components are wrapped within it, as a CHILDREN. As a result, any code we write within this file, will be displayed on every route page we create. This unique file enables us to personalize the behavior of our application by providing a COMMON LAYOUT or TEMPLATE for all of the pages.

  => Any component we include in this file, will be shared throughout the entire application.
*/

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
