/* 
  => This file is the main entry point of our application, and all the components are wrapped within it, as a CHILDREN. As a result, any code we write within this file, will be displayed on every route page we create. This unique file enables us to personalize the behavior of our application by providing a COMMON LAYOUT or TEMPLATE for all of the pages.

  => Any component we include in this file, will be shared throughout the entire application.

  => This Root Layout is SERVER-RENDERED, ensuring faster page loads and better SEO.

  => We cannot use client component viz. Header directly into the server component viz. layout.tsx (RootLayout), because it's not allowed

  => "children" represent any content or components that are rendered inside the ClientLayout component.

*/

import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ClientLayout from "@/components/ClientLayout";
import Sidebar from "@/components/Sidebar";

// Provide metadata for SEO and browser display, such as the title & description
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // Wrapping application in Clerk's Authentication Context, allowing components like useUser to work anywhere inside it.
        <ClerkProvider>
            <html lang="en">
                <body>
                    <ClientLayout>  {/* Renders ClientLayout Component (viz. a client component, so it will render on the client side!) */}

                        <div className="flex min-h-screen">
                            <Sidebar />


                            {/* flex-1: means use up all the space */}
                            <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scroll">
                                {children}  {/* page.tsx component content */}
                            </div>
                        </div>

                    </ClientLayout>
                </body>
            </html>
        </ClerkProvider>
    );
}
